### ISSUE TITLE
adding to catalog fails

### ISSUE THREAD

**Issue by Alexuisis** [cloudsoft/brooklyn-hyperledger#34]
Hi Guys, really stuck on this:

>  Could not resolve item 'hyperledger-services-host': Transformer for Brooklyn OASIS CAMP interpreter gave an error creating this plan: Unable to match plan item: Service[name=Membership Services and CLI Docker Host,description=<null>,serviceType=hyperledger-docker-engine,characteristics=[],customAttributes={brooklyn.children=[{type=hyperledger-membersrvc-node, id=my-hyperledger-membersrvc-node}, {type=hyperledger-cli-node, id=my-hyperledger-cli-node}, {type=hyperledger-sequence-node, id=my-hyperledger-sequence-node}]}]

Can you please advise?

**Comment by mikezaccardo** [comment]
Hi, at what step in the process does this message appear? Is it on deployment or adding Hyperledger to the catalog? Also, which release of Brooklyn or AMP are you using? Thanks.
